theme: jekyll-theme-cayman
title: [Hausi Müller for IEEE Division Delegate-Elect]
description: [For IEEE Division Delegate-Elect/Director-Elect, 2020 IEEE Division Delegate/Director, 2021-2022 Division VIII (Computer)]

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - ACCOMPLISHMENTS.md
  - STATEMENT.md
