theme: jekyll-theme-cayman
title: [Hausi Müller for IEEE Division Delegate-Elect]
description: [For IEEE Division Delegate-Elect/Director-Elect, 2020 IEEE Division Delegate/Director, 2021-2022 Division VIII (Computer)]
